windowrule {
  name = nmtui-popup
  match:title = nmtui

  float = on
  center = on
  size = 1024 800
}

windowrule {
  name = bluetooth-popup
  match:class = blueman-manager

  float = on
  center = on
}

windowrule {
  name = speaker-popup
  match:title = pipemixer 

  float = on
  center = on
}
