source = ~/.config/hypr/hyprconf/bindings.conf
source = ~/.config/hypr/hyprconf/monitors.conf
source = ~/.config/hypr/hyprconf/looks.conf
source = ~/.config/hypr/hyprconf/rules.conf
source = ~/.config/hypr/hyprconf/inputs.conf

# env = HYPRCURSOR_THEME,BreezeX-Dark
# env = HYPRCURSOR_SIZE,24
# env = XCURSOR_SIZE, 24
# env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
# env = ELECTRON_OZONE_PLATFORM_HINT,wayland
# env = GTK_THEME, Adwaita-dark

# exec = /home/hades/.dotfiles/.scripts/dock/monitors.sh
# exec = systemctl --user start dock.service
exec = systemctl --user start xdg-desktop-portal-gtk
exec = easyeffects --gapplication-service
# exec-once = hyprctl setcursor Nordzy-hyprcursors 32
exec-once = udiskie
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

xwayland {
    force_zero_scaling = true
}

dwindle {
    # pseudotile     = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    focus_on_activate = true
    force_default_wallpaper  = 0
    disable_hyprland_logo    = true
    disable_splash_rendering = true
}
