#!/usr/bin/env ruby


output = `xrandr`

if ARGV[0] == "shutdown"
  `/usr/bin/ln -sf /home/odin/.dotfiles/.config/hypr/setups/laptop.conf /home/odin/.dotfiles/.config/hypr/hyprland.conf`
elsif output.scan("DP").count > 1
  `/usr/bin/ln -sf /home/odin/.dotfiles/.config/hypr/setups/dock.conf /home/odin/.dotfiles/.config/hypr/hyprland.conf`
else
  `/usr/bin/ln -sf /home/odin/.dotfiles/.config/hypr/setups/laptop.conf /home/odin/.dotfiles/.config/hypr/hyprland.conf`
end
